/**
 * Chronic Conditions / ICD-10 Diagnoses constants
 * These constants define the predefined list of chronic conditions and diagnoses
 * available for beneficiary details in the system
 */
export const CHRONIC_CONDITIONS = {
  CA_RENALIS: { code: 'C64', label: 'Ca Renalis (Kidney Cancer)' },
  PNEUMONIA: { code: 'J18', label: 'Pneumonia' },
  HERNIA_DISCI: { code: 'M51', label: 'Hernia disci L5/S1' },
  BRONCHITIS_OBSTRUCTIVA: { code: 'J44', label: 'Bronchitis obstructiva' },
  POLYARTHROSIS: { code: 'M15', label: 'Polyarthrosis' },
  ST_POST_CRANIOTOMY: { code: 'Z98.89', label: 'Status post craniotomy' },
  SKLEROSIS_MULTIPLEX: { code: 'G35', label: 'Sklerosis multiplex (Multiple Sclerosis)' },
  ASTHMA: { code: 'J45', label: 'Asthma' },
  ST_POST_ICVI: { code: 'I63', label: 'Status post ICVI (Stroke)' },
  HIPERTENSION_ARTERIAL: { code: 'I10', label: 'Hipertension arterial' },
  GANGRENA_ISCAEMICA: { code: 'I96', label: 'Gangrena iscaemica' },
  EPILEPSIA: { code: 'G40', label: 'Epilepsia (Epilepsy)' },
  DERMATITIS_ULCEROSA: { code: 'L88', label: 'Dermatitis Ulcerosa' },
  ADENOCA_VENTRICULI_BENIGN: { code: 'D33', label: 'Adenocarcinoma Ventriculi (Benign)' },
  ADENOCA_VENTRICULI_MALIGN: { code: 'C71', label: 'Adenocarcinoma Ventriculi (Malign)' },
  GASTRITIS_CHRONICA: { code: 'K29', label: 'Gastritis chronica' },
  RUPTURA_ACL: { code: 'S72', label: 'Ruptura ACL (Anterior Cruciate Ligament)' },
  MYALGJI: { code: 'M79.6', label: 'Myalgji (Myalgia)' },
  CYSTITIS: { code: 'N30', label: 'Cystitis' },
  CA_PULMONUM: { code: 'C34', label: 'Ca Pulmonum (Lung Cancer)' },
  FRACTURA_ACETABULI: { code: 'S72', label: 'Fractura acetabuli' },
  BRONCHITIS: { code: 'J44', label: 'Bronchitis' },
  ITU: { code: 'N39', label: 'Infeksion i traktit urinar (UTI)' },
  BRONCHOPNEUMONIA: { code: 'J18', label: 'Bronchopneumonia' },
  INSUFF_RENALIS_ACUTA: { code: 'N17', label: 'Insufficienca renalis acuta' },
  TU_RENIS: { code: 'C64', label: 'Tumor renis (Kidney Tumor)' },
  TONSILLOPHARYNGITIS: { code: 'J03', label: 'Tonsillopharyngitis' },
  GONARTROSIS: { code: 'M17.9', label: 'Gonartrosis' },
  DIABETES_TIP_II: { code: 'E11', label: 'Diabetes mellitus tip II' },
  KOLLI_PERTUSIS: { code: 'R05', label: 'Kollë (Cough/Pertussis)' },
  ADENOMA_RECTI: { code: 'D12.7', label: 'Adenoma recti' },
  ENCEPHALOPATHIA_VASCULARIS: { code: 'G93.4', label: 'Encephalopathia vascularis' },
  HEMIPARESIS: { code: 'I69.3', label: 'Hemiparesis' },
  DIABETES_TIP_I: { code: 'E10', label: 'Diabetes mellitus tip I' },
  VIZITE_E_RREGULLT: { code: 'Z01', label: 'Vizitë e rregullt (Regular visit)' },
  ST_POST_AMPUTATIO: { code: 'Z89', label: 'Status post amputatio' },
  FRACTURA_COLLI_FEMORIS: { code: 'S72', label: 'Fractura colli femoris' },
  ICVI: { code: 'I63', label: 'ICVI (Cerebrovascular Accident)' },
  FISTULA_COXOFEMORIS: { code: 'S71', label: 'Fistula regio coxofemoris' },
  POLYTRAUMA: { code: 'T07', label: 'Polytrauma' },
  DILATATIO_AORTAE: { code: 'I71', label: 'Dilatatio aortae ascendens' },
  INSUFFICIENTIA_CORDIS: { code: 'I50', label: 'Insufficienca cordis decompensata NYHA III' },
  FRACTURA_FOSA_GLENOIDALE: { code: 'S42.1', label: 'Fractura fosa glenoidale' },
  GANGRENA_APICALIS: { code: 'I96', label: 'Gangrena apicalis digitorum pedis' },
  ARTHRITIS_SEPTICA: { code: 'M00.8', label: 'Arthritis septica' },
  CEPHALEA: { code: 'R51', label: 'Cephalea (Headache)' },
  HERNIA_INGUINALIS: { code: 'K40.9', label: 'Hernia inguinalis' },
  ADENOCARCINOMA_PULMO_HEPATIS: { code: 'C22', label: 'Adenocarcinoma pulmo/hepatis' },
  PHLEGMONA: { code: 'L02', label: 'Phlegmona' },
  TU_CRANII: { code: 'S06.9', label: 'Tumor cranii' },
  MYOMA_UTERI: { code: 'D25', label: 'Myoma uteri' },
  RUPTURA_LCA_BUCKET_HANDLE: { code: 'D17.2', label: 'Ruptura LCA et bucket handle tear' },
  FRACTURA_HUMERI: { code: 'S42', label: 'Fractura humeri' },
  INFLUENCA: { code: 'J11', label: 'Influenca (Influenza)' },
  CYSTOCOLLOCOELLA: { code: 'N81.1', label: 'Cystocollocoella' },
  ARTHROSIS_GENI: { code: 'M17', label: 'Arthrosis geni' },
  GASTROENTEROCOLITIS: { code: 'A09', label: 'Gastroenterocolitis' },
  ST_POST_CYSTOCOLLA: { code: 'N81.1', label: 'Status post op. Cystocolle' },
  HERNIA_INGUINALIS_BILL: { code: 'K40.9', label: 'Hernia inguinalis bilateral' },
  SCHIZOPHRENIA: { code: 'F20', label: 'Schizophrenia' },
  ST_POST_V_MITRALIS: { code: 'Z95.2', label: 'Status post implantationem valvulae mitralis' },
  BRONCHITIS_ACUTA: { code: 'J40', label: 'Bronchitis acuta' },
  CAUDA_EQUINA: { code: 'G83.4', label: 'Cauda Equina syndrome' },
  TONSILLITIS_ACUTA: { code: 'J03.9', label: 'Tonsillitis acuta' },
  CA_HEPATIS: { code: 'C22', label: 'Ca Hepatis (Liver Cancer)' },
  CA_PELVIS: { code: 'C76.3', label: 'Ca Pelvis' },
  LUMBOISCHIALGIA: { code: 'M54.4', label: 'Lumboischialgia' },
  PIURIA: { code: 'R82.8', label: 'Piuria' },
  M_ALZHEIMER: { code: 'G30', label: 'Morbus Alzheimer' },
  VENTER_PENDULANS: { code: 'K43.9', label: 'Venter pendulans' },
  FATIGUE: { code: 'R53', label: 'Fatigue (Lodhje)' },
  CA_MAMMAE: { code: 'C50', label: 'Ca Mammae (Breast Cancer)' },
  VOMITUS: { code: 'R11', label: 'Vomitus (Vomiting)' },
  SYNDROMUM_VERTIGINOSUM: { code: 'R42', label: 'Syndromum vertiginosum (Vertigo)' },
  TU_OVARII: { code: 'C56', label: 'Tumor ovarii' },
  CARCINOMATOSIS_PERITONEI: { code: 'C48.2', label: 'Carcinomatosis peritonei' },
  ABDOMEN_ACUTUM: { code: 'R10.0', label: 'Abdomen acutum' },
  CHOLECYSTITIS_ACUTA: { code: 'K81', label: 'Cholecystitis acuta' },
  STASIS_RENIS: { code: 'N28.9', label: 'Stasis renis' },
  BRONCHITIS_ACUTA_J20: { code: 'J20', label: 'Bronchitis acuta' },
  INFILTRATIO_PULMONIS: { code: 'J18.9', label: 'Infiltratio pulmonis' },
  CANDIDIASIS: { code: 'B37', label: 'Candidiasis' },
  DHIMBJE_E_PASPECIFIKUAR: { code: 'R52', label: 'Dhimbje e paspecifikuar (Unspecified pain)' },
  STRESI_POSTTRAUMATIK: { code: 'F43', label: 'Stresi postraumatik (PTSD)' },
  CA_LUKTHI: { code: 'C16', label: 'Ca Lukthi (Stomach Cancer)' },
  ABUZIMI_ME_ALKOOL: { code: 'F10', label: 'Abuzimi me alkool (Alcohol abuse)' },
  CA_UTERI: { code: 'C54', label: 'Ca Uteri (Uterine Cancer)' },
  TJETER: { code: 'OTHER', label: 'Tjetër / DG jo e saktë / jo e kuptueshme (Other)' },
} as const;

/**
 * Array of all chronic condition objects
 */
export const CHRONIC_CONDITION_VALUES = Object.entries(CHRONIC_CONDITIONS).map(([key, value]) => ({
  id: key,
  ...value,
}));

/**
 * Type for chronic condition
 */
export type ChronicCondition = typeof CHRONIC_CONDITION_VALUES[number];

export default { CHRONIC_CONDITIONS, CHRONIC_CONDITION_VALUES };
